"""Task prompt strings for all 6 pipeline agents."""
from __future__ import annotations

from article_generator.constants import COVER_AUTHOR, COVER_COURSE, COVER_LECTURER

_RESEARCH_DESC = (
    "Research the topic: '{topic}'.\n"
    "Use SerperDevTool to run ≥ 3 distinct Google searches covering different "
    "aspects of the topic. Extract ≥ 5 credible references (author, title, year, "
    "URL). Organise findings into a structured outline: suggested title, chapter "
    "descriptions with key facts, and full reference list in [AuthorYear] format."
)
_RESEARCH_OUT = (
    "Structured research outline with: suggested article title, ≥ 4 chapter "
    "descriptions with key facts, and ≥ 5 references each with author, title, "
    "year, and URL in [AuthorYear] citation format."
)

_WRITE_DESC = (
    "Using ONLY the researcher's outline, write a complete academic article in Markdown "
    "on: '{topic}'.\n\n"
    "LANGUAGE — CRITICAL REQUIREMENT:\n"
    "  ALL prose MUST be written in Hebrew Unicode script (right-to-left characters).\n"
    "  CORRECT example heading:  ## תקציר\n"
    "  CORRECT example sentence: מערכות רב-סוכניות (MAS) הן פרדיגמה מרכזית בבינה מלאכותית...\n"
    "  English appears ONLY for: technical terms (LLM, API, MAS), code, variable names, citations.\n"
    "  DO NOT write full English sentences or paragraphs.\n"
    "  DO NOT use LaTeX commands (\\begin{{english}}, \\LR{{}}, \\section{{}}) — this is Markdown.\n\n"
    "MANDATORY SECTIONS — write ALL in order (missing or truncated section = TASK FAILURE):\n"
    "  1. Cover block in Hebrew: title, author (" + COVER_AUTHOR + "), date, "
    "course (" + COVER_COURSE + "), lecturer (" + COVER_LECTURER + ")\n"
    "  2. ## תקציר — ≥ 400 Hebrew words\n"
    "  3. ## הקדמה — ≥ 1,000 Hebrew words\n"
    "  4. ## פרק 1: [Hebrew title from outline] — ≥ 1,200 Hebrew words\n"
    "  5. ## פרק 2: [Hebrew title from outline] — ≥ 1,200 Hebrew words\n"
    "  6. ## פרק 3: [Hebrew title from outline] — ≥ 1,200 Hebrew words\n"
    "  7. ## פרק 4: [Hebrew title from outline] — ≥ 1,200 Hebrew words\n"
    "  8. ## מסקנות — ≥ 600 Hebrew words\n"
    "  9. ## ביבליוגרפיה — every reference from the outline in [AuthorYear] format\n\n"
    "VISUAL ELEMENTS (embed inside chapters):\n"
    "  - ≥ 1 Markdown table: | col | col | format\n"
    "  - ≥ 1 formula placeholder: <!-- FORMULA: describe the formula -->\n"
    "  - ≥ 1 graph placeholder: [GRAPH: describe the graph]\n\n"
    "ANTI-TRUNCATION RULE: Write every section to its FULL minimum length before moving "
    "to the next. Do NOT write '[continued]', '[truncated]', '[see full version]', or any "
    "placeholder text in place of real content. If you are running low on space, write "
    "shorter but COMPLETE paragraphs — every section must appear in full. "
    "Total article MUST reach ≥ 8,000 Hebrew words. Output the entire article now."
)
_WRITE_OUT = (
    "Complete Markdown article (≥ 8,000 Hebrew words, ≥ 15 pages when compiled). "
    "All 9 sections present and fully written in Hebrew (≥ 90%% prose). "
    "Includes ≥ 1 table, ≥ 1 formula placeholder, ≥ 1 graph placeholder, "
    "and all citations in [AuthorYear] format. No truncated or placeholder sections."
)

_REVIEW_DESC = (
    "Review and improve the writer's Markdown article. Fix plain-text formula words "
    "(e.g. 'sigma' → '$\\sigma$', 'integral' → '$\\int$'). Remove weak language "
    "('very', 'basically', 'obviously'). Improve clarity and academic tone. "
    "IMPORTANT: Do NOT translate Hebrew to English — the article must remain primarily "
    "in Hebrew (≥ 90% Hebrew prose). If content was accidentally shortened, restore it "
    "to the full ≥ 8,000-word length. "
    "Do NOT remove or alter [AuthorYear] citations, tables, formula placeholders, "
    "graph placeholders, Hebrew text, or any structural section."
)
_REVIEW_OUT = (
    "Revised Markdown article with improved academic tone and clarity. "
    "Still primarily in Hebrew (≥ 90% prose). Full length maintained (≥ 8,000 words). "
    "All structural elements preserved: table, formula placeholders, graph "
    "placeholder, Hebrew content, and all [AuthorYear] citations intact."
)

_GRAPH_DESC = (
    "You receive the COMPLETE reviewed article from the previous agent. Do TWO things:\n"
    "STEP 1 — TWO FIGURES (one matplotlib script, executed once via LocalCodeInterpreterTool, "
    "EXIT CODE: 0). First line matplotlib.use('Agg'); CLEAN WHITE background on every figure "
    "and axes (facecolor='white'; NO dark theme); no plt.show(). Produce BOTH files:\n"
    "  (a) figures/graph.pdf — a DATA visualisation (bar/line/scatter etc.) relevant to the "
    "article, with axis labels and a title. Save: "
    "plt.savefig('figures/graph.pdf', facecolor='white', bbox_inches='tight').\n"
    "  (b) figures/diagram.pdf — a SCHEMATIC ILLUSTRATION (an 'image', NOT a data chart): a "
    "labelled architecture/block diagram of a multi-agent system, drawn with matplotlib "
    "boxes (patches.FancyBboxPatch/Rectangle) and arrows (annotate), axis turned off "
    "(ax.axis('off')). Save: "
    "plt.savefig('figures/diagram.pdf', facecolor='white', bbox_inches='tight').\n"
    "Confirm BOTH files exist with EXIT CODE: 0 before continuing.\n"
    "STEP 2 — PASS THE ARTICLE THROUGH: Your FINAL ANSWER must be the COMPLETE reviewed "
    "article reproduced VERBATIM and IN FULL — every section, paragraph and reference, "
    "exactly as received, with NOTHING summarised, shortened, paraphrased or omitted. The "
    "next agent (LaTeX) builds the document from your answer, so the entire article text "
    "MUST be present. After the full article, append the single line "
    "'[FIGURES READY: figures/diagram.pdf, figures/graph.pdf]'."
)
_GRAPH_OUT = (
    "The COMPLETE reviewed article reproduced verbatim and in full (no section, paragraph "
    "or reference removed or shortened), followed by the line "
    "'[FIGURES READY: figures/diagram.pdf, figures/graph.pdf]' confirming BOTH matplotlib "
    "figures (a schematic diagram image and a data graph, white background) were generated "
    "with EXIT CODE: 0."
)

_LATEX_DESC = (
    "Transcribe the FULL reviewed article (the text preceding any '[GRAPH READY...]' "
    "marker) into a complete XeLaTeX .tex document, Hebrew as the MAIN language and English "
    "secondary. Include EVERY section and EVERY paragraph IN FULL — do NOT summarise, "
    "condense, shorten, paraphrase or drop any content; only add LaTeX markup around the "
    "existing text. The article is long (~15 pages); reproduce all of it.\n"
    "FONTS (non-negotiable — installed on the system): "
    "\\setmainfont{Times New Roman}, \\setsansfont{Arial}, \\setmonofont{Courier New}, "
    "\\newfontfamily\\hebrewfont{Arial}[Script=Hebrew]. "
    "Do NOT use FreeSerif, Linux Libertine, or any other font.\n"
    "PREAMBLE (this exact order): fontspec (with the fonts above), polyglossia "
    "(\\setmainlanguage{hebrew}, \\setotherlanguage{english}), geometry, fancyhdr, "
    "graphicx, xcolor, amsmath+amssymb, booktabs+tabularx, biblatex (backend=biber, "
    "style=authoryear) with \\addbibresource{references.bib}, and hyperref LAST.\n"
    "CRITICAL RTL RULES — breaking ANY of these corrupts the whole page layout:\n"
    "  1. Do NOT \\usepackage{bidi}. polyglossia already provides RTL; loading bidi again "
    "shifts every line off the page. Never load bidi.\n"
    "  2. Do NOT use tikz or \\begin{tikzpicture} ANYWHERE, and do NOT \\usepackage{tikz}. "
    "tikz inside an RTL document corrupts text direction for everything after it. For any "
    "horizontal line (e.g. on the title page) use \\rule{\\textwidth}{2pt}.\n"
    "  3. The bibliography MUST render left-to-right: end the document with exactly "
    "\\begin{english}\\printbibliography\\end{english} (never a bare \\printbibliography).\n"
    "TITLE PAGE — use \\begin{titlepage} with \\centering. Show the Hebrew title, a short "
    "Hebrew subtitle, then a cover-info block with these FIVE fields, each on its own line, "
    "Latin text wrapped in \\LR{...}:\n"
    "  נושא/Topic (the title), "
    "מחבר/Author: \\LR{" + COVER_AUTHOR + "}, "
    "תאריך/Date: \\LR{\\today}, "
    "קורס/Course: \\LR{" + COVER_COURSE + "}, "
    "מרצה/Lecturer: \\LR{" + COVER_LECTURER + "}.\n"
    "The title page contains ONLY a \\rule, the title, the subtitle and this cover block. "
    "Do NOT put \\includegraphics, the graph, or any figure on the title page.\n"
    "After the title page add \\tableofcontents, and set fancyhdr headers/footers.\n"
    "CONTENT RULES: Hebrew body text goes directly (Hebrew is default). Wrap English "
    "paragraphs/sections in \\begin{english}...\\end{english}. Inline English terms use "
    "\\LR{...}. Math inside Hebrew text uses \\LR{$...$}. Tables use tabularx within "
    "\\textwidth so they never exceed the margins.\n"
    "Replace formula placeholders with real math environments (equation/align). "
    "Embed BOTH figures in the BODY (never on the title page), each in its own "
    "\\begin{figure}[h] with a \\caption: (1) the schematic illustration "
    "\\includegraphics[width=0.85\\textwidth]{figures/diagram.pdf} in an early "
    "architecture section, and (2) the data graph "
    "\\includegraphics[width=\\textwidth]{figures/graph.pdf}. "
    "Convert [AuthorYear] -> \\cite{authoryear}.\n"
    "OUTPUT: Write the COMPLETE .tex file to results/article.tex via FileWriterTool. "
    "Then output ONLY a short confirmation message (file path + byte count). "
    "Do NOT output the LaTeX content itself — only write it to disk."
)
_LATEX_OUT = (
    "Confirmation message: 'Written results/article.tex — N bytes'. "
    "The file at results/article.tex is a complete XeLaTeX document with: "
    "\\setmainlanguage{hebrew}; a title page showing Topic, Author, Date, Course and "
    "Lecturer; \\tableofcontents; fancyhdr headers/footers; >= 1 equation; >= 1 tabularx "
    "table within \\textwidth; TWO figures (figures/diagram.pdf schematic image and "
    "figures/graph.pdf data graph), each in a \\begin{figure} with a caption; Hebrew body "
    "text; \\cite{} commands; and the bibliography as \\begin{english}\\printbibliography"
    "\\end{english}. It contains NO \\usepackage{bidi} and NO tikz/tikzpicture."
)

_BIDI_DESC = (
    "Read results/article.tex via FileReadTool. Fix RTL/BiDi STRUCTURAL issues only. "
    "DO NOT translate or rewrite article content; preserve the language exactly.\n"
    "Apply ALL of these fixes wherever they apply:\n"
    "1. If the preamble contains \\usepackage{bidi}, DELETE that line. polyglossia already "
    "provides RTL; a second bidi load shifts every line off the page (severe bug).\n"
    "2. If there is \\usepackage{tikz}, \\usetikzlibrary{...}, or any "
    "\\begin{tikzpicture}...\\end{tikzpicture}, REMOVE it. Replace a decorative tikz "
    "horizontal line with \\rule{\\textwidth}{2pt}. tikz in an RTL document corrupts layout.\n"
    "3. The bibliography MUST be left-to-right: ensure the document ends with "
    "\\begin{english}\\printbibliography\\end{english}. If it is a bare \\printbibliography, "
    "wrap it in \\begin{english}...\\end{english}.\n"
    "4. Unguarded inline math ($...$) inside Hebrew text — wrap with \\LR{$...$}. Keep Hebrew "
    "body text as the main (default) language; do not add \\setmainlanguage or \\begin{hebrew}.\n"
    "5. If the title page does NOT already list the author, course and lecturer, ADD a cover "
    "block on the title page with these lines (Latin wrapped in \\LR{}): "
    "מחבר/Author: \\LR{" + COVER_AUTHOR + "}, "
    "תאריך/Date: \\LR{\\today}, "
    "קורס/Course: \\LR{" + COVER_COURSE + "}, "
    "מרצה/Lecturer: \\LR{" + COVER_LECTURER + "}.\n"
    "6. The title page (\\begin{titlepage}...\\end{titlepage}) must NOT contain any "
    "\\includegraphics or figure. If figures/graph.pdf is included inside the titlepage, "
    "DELETE that \\includegraphics line — the graph belongs only in the body.\n"
    "Write the COMPLETE corrected file back to results/article.tex via FileWriterTool. "
    "Then output ONLY a short report (no LaTeX content): "
    "'BiDi fix complete: N issues found, N fixed. results/article.tex updated.'"
)
_BIDI_OUT = (
    "Short confirmation report: 'BiDi fix complete: N issues found, N fixed. "
    "results/article.tex updated.' "
    "The corrected file preserves the article's original language structure exactly. "
    "Only BiDi structural markup was adjusted; no content was added or translated."
)
