from __future__ import annotations

import logging
import subprocess
import time
from pathlib import Path

from article_generator.constants import (
    ARTICLE_TEX_FILE,
    BIBER_EXECUTABLE,
    BIBER_TIMEOUT_SECONDS,
    LATEX_ENGINE,
    LATEX_TIMEOUT_SECONDS,
)
from article_generator.services.latex_doc_builder import (
    build_document,
    format_bib_entry,
    validate_markdown,
    validate_reference,
)
from article_generator.services.latex_models import (
    _WARNING_PATTERNS,
    ArticleConfig,
    ArticlePaths,
    BibGenerationError,
    CompilationError,
    CompilationResult,
    CompilationTimeoutError,
    LaTeXGenerationError,
    Reference,
)
from article_generator.services.latex_tex_renderer import convert_body

__all__ = ["ArticleConfig", "ArticlePaths", "Reference", "CompilationResult",
           "LaTeXGenerationError", "BibGenerationError", "CompilationError",
           "CompilationTimeoutError", "LaTeXCompiler"]

logger = logging.getLogger(__name__)


class LaTeXCompiler:
    """Produces .tex/.bib files from Markdown and compiles to PDF via XeLaTeX.

    T-054: generate_tex()  — Markdown → .tex with full preamble.
    T-055: generate_bib()  — reference list → .bib file.
    T-056: compile()       — 4-pass XeLaTeX + biber compilation.
    """

    def __init__(self, output_dir: Path | None = None, assets_dir: Path | None = None) -> None:
        from article_generator.constants import ASSETS_DIR, RESULTS_DIR
        self._output_dir = Path(output_dir) if output_dir is not None else RESULTS_DIR
        self._assets_dir = Path(assets_dir) if assets_dir is not None else ASSETS_DIR

    def generate_tex(self, markdown: str, config: ArticleConfig) -> str:
        """Convert *markdown* to a complete LaTeX document and write to disk."""
        validate_markdown(markdown)
        body = convert_body(markdown)
        tex = build_document(body, config)
        output_path = Path(config.paths.output_dir) / ARTICLE_TEX_FILE
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(tex, encoding="utf-8")
        logger.info("LaTeXCompiler: wrote %s (%d bytes)", output_path, len(tex.encode()))
        return tex

    def generate_bib(self, references: list[Reference], config: ArticleConfig) -> str:
        """Produce a valid .bib file from *references* and write to disk."""
        for ref in references:
            validate_reference(ref)
        entries = [format_bib_entry(ref) for ref in references]
        bib_content = (
            "% Generated by LaTeXCompiler — do not edit manually\n\n"
            + "\n\n".join(entries)
            + ("\n" if entries else "")
        )
        output_path = Path(config.paths.output_dir) / config.paths.bib_filename
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(bib_content, encoding="utf-8")
        logger.info("LaTeXCompiler: wrote %s (%d entries)", output_path, len(references))
        return bib_content

    def compile(self, tex_path: str, bib_path: str) -> CompilationResult:
        """Run 4-pass LuaLaTeX + biber pipeline; return CompilationResult."""
        tex = Path(tex_path)
        if not tex.exists():
            raise FileNotFoundError(f"tex file not found: {tex}")
        work_dir = tex.parent
        stem = tex.stem
        log_path = work_dir / f"{stem}.log"
        pdf_path = work_dir / f"{stem}.pdf"
        result = CompilationResult(
            success=False, passes_completed=0, pdf_path=None,
            errors=[], warnings=[], log_path=None, duration_seconds=0.0,
        )
        start = time.monotonic()
        passes_done = 0
        try:
            self._run_latex_engine(tex, work_dir, result); passes_done = 1  # noqa: E702
            self._run_biber(stem, work_dir, result);        passes_done = 2  # noqa: E702
            self._run_latex_engine(tex, work_dir, result); passes_done = 3  # noqa: E702
            self._run_latex_engine(tex, work_dir, result); passes_done = 4  # noqa: E702
        except CompilationError as exc:
            result.passes_completed = passes_done
            result.duration_seconds = time.monotonic() - start
            result.log_path = log_path if log_path.exists() else None
            exc.result = result
            raise
        result.passes_completed = passes_done
        result.success = pdf_path.exists()
        result.pdf_path = pdf_path if pdf_path.exists() else None
        result.log_path = log_path if log_path.exists() else None
        result.duration_seconds = time.monotonic() - start
        logger.info(
            "LaTeXCompiler: %s — %d passes, %.1fs",
            "OK" if result.success else "no PDF", passes_done, result.duration_seconds,
        )
        return result

    def _run_latex_engine(self, tex: Path, work_dir: Path, result: CompilationResult) -> None:
        log_path = work_dir / f"{tex.stem}.log"
        try:
            proc = subprocess.run(
                [LATEX_ENGINE, "--interaction=nonstopmode", tex.name],
                cwd=work_dir, capture_output=True, encoding="utf-8",
                errors="replace", timeout=LATEX_TIMEOUT_SECONDS,
            )
        except subprocess.TimeoutExpired as exc:
            raise CompilationTimeoutError(
                f"{LATEX_ENGINE} timed out after {LATEX_TIMEOUT_SECONDS}s"
            ) from exc
        errors = self._log_errors(log_path)
        result.warnings.extend(self._log_warnings(log_path))
        if proc.returncode != 0 or errors:
            result.errors.extend(errors or [f"{LATEX_ENGINE} exited with code {proc.returncode}"])
            raise CompilationError(f"XeLaTeX pass failed: {result.errors[0]}")

    def _run_biber(self, stem: str, work_dir: Path, result: CompilationResult) -> None:
        try:
            proc = subprocess.run(
                [BIBER_EXECUTABLE, stem],
                cwd=work_dir, capture_output=True, encoding="utf-8",
                errors="replace", timeout=BIBER_TIMEOUT_SECONDS,
            )
        except subprocess.TimeoutExpired as exc:
            raise CompilationTimeoutError(
                f"biber timed out after {BIBER_TIMEOUT_SECONDS}s"
            ) from exc
        if proc.returncode != 0:
            msg = (proc.stderr or proc.stdout or "biber failed").strip()[:300]
            result.errors.append(msg)
            raise CompilationError(f"biber pass failed: {msg}")

    @staticmethod
    def _log_errors(log_path: Path) -> list[str]:
        if not log_path.exists():
            return []
        return [ln for ln in log_path.read_text(encoding="utf-8", errors="replace").splitlines()
                if ln.startswith("!")]

    @staticmethod
    def _log_warnings(log_path: Path) -> list[str]:
        if not log_path.exists():
            return []
        return [ln for ln in log_path.read_text(encoding="utf-8", errors="replace").splitlines()
                if any(pat in ln for pat in _WARNING_PATTERNS)]
